### create new event
POST http://localhost:8080/events
Accept: application/json
Content-Type: application/json

{
	"title": "title goes here",
	"description": "test description goes here",
	"imageUrl": "https://picsum.photos/200/300",
	"videoUrl": null
}