### get presigned s3 url for upload
POST http://localhost:8080/s3/signature
Accept: application/json
Content-Type: application/json

{
    "eventId": 1,
	"fileName": "image.png",
	"fileType": "png"
}
